package kg.giftlist.giftlistm2.enums;

public enum ComplaintsType {

    VIOLENCE,
    MANIFESTATION_OF_HATRED,
    ILLEGAL_ACTIVITIES_OR_REGULATED_GOODS,
    SPAM,
    CALLS_FOR_VIOLENCE_DANGEROUS_ACTIONS,
    SCENES_OF_A_PORNOGRAPHIC_NATURE,
    OTHER

}
